-- MySQL Script generated by MySQL Workbench
-- Mon 24 Aug 2020 14:25:18 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`patient` (
  `id_patient` INT NOT NULL,
  `naam` VARCHAR(60) NOT NULL,
  `sex` VARCHAR(45) NOT NULL,
  `age_diagonse` INT NOT NULL,
  PRIMARY KEY (`id_patient`),
  UNIQUE INDEX `id_patient_UNIQUE` (`id_patient` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gene` (
  `id_Gene` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Gene`),
  UNIQUE INDEX `id_Gene_UNIQUE` (`id_Gene` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mutation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mutation` (
  `id_Mutation` INT NOT NULL AUTO_INCREMENT,
  `Chromosomal location` VARCHAR(255) NOT NULL,
  `Gene_id_Gene` INT NOT NULL,
  PRIMARY KEY (`id_Mutation`),
  UNIQUE INDEX `id_Mutation_UNIQUE` (`id_Mutation` ASC) VISIBLE,
  INDEX `fk_Mutation_Gene1_idx` (`Gene_id_Gene` ASC) VISIBLE,
  CONSTRAINT `fk_Mutation_Gene1`
    FOREIGN KEY (`Gene_id_Gene`)
    REFERENCES `mydb`.`Gene` (`id_Gene`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`patient_has_Gene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`patient_has_Gene` (
  `patient_id_patient` INT NOT NULL,
  `Gene_id_Gene` INT NOT NULL,
  PRIMARY KEY (`patient_id_patient`, `Gene_id_Gene`),
  INDEX `fk_patient_has_Gene_Gene1_idx` (`Gene_id_Gene` ASC) VISIBLE,
  INDEX `fk_patient_has_Gene_patient1_idx` (`patient_id_patient` ASC) VISIBLE,
  CONSTRAINT `fk_patient_has_Gene_patient1`
    FOREIGN KEY (`patient_id_patient`)
    REFERENCES `mydb`.`patient` (`id_patient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_has_Gene_Gene1`
    FOREIGN KEY (`Gene_id_Gene`)
    REFERENCES `mydb`.`Gene` (`id_Gene`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
